on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2
        with:
          spec: './main.spec'
          requirements: './requirements.txt'
          upload_exe_with_name: 'Topdown'
