name: Package With PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: './main.spec'
          requirements: './requirements.txt'
          upload_exe_with_name: 'Topdown_Linux'
  windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: './main.spec'
          requirements: './requirements.txt'
          upload_exe_with_name: 'Topdown_Windows'
